### ISSUE TITLE
Error when running wsdd command

### ISSUE THREAD

**Issue by Spectroxx** [christgau/wsdd#117]
Hello, I'm trying to run `wsdd` on popOS, after installing and executing it I receive the error below.
Any help would be greatly appreciated!
```
2021-07-24 16:45:55,950:wsdd WARNING(pid 12798): no interface given, using all interfaces
2021-07-24 16:45:55,951:asyncio ERROR(pid 12798): Exception in callback NetlinkAddressMonitor.handle_request()
handle: <Handle NetlinkAddressMonitor.handle_request()>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/wsdd", line 1397, in handle_request
    self.handle_new_address(addr, ifa_family, iface)
  File "/usr/bin/wsdd", line 1164, in handle_new_address
    self.http_servers.append(WSDHttpServer(
  File "/usr/bin/wsdd", line 905, in __init__
    super().__init__(mch.listen_address, RequestHandlerClass)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/bin/wsdd", line 911, in server_bind
    super().server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
2021-07-24 16:45:55,952:asyncio ERROR(pid 12798): Exception in callback NetlinkAddressMonitor.handle_request()
handle: <Handle NetlinkAddressMonitor.handle_request()>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/bin/wsdd", line 1397, in handle_request
    self.handle_new_address(addr, ifa_family, iface)
  File "/usr/bin/wsdd", line 1164, in handle_new_address
    self.http_servers.append(WSDHttpServer(
  File "/usr/bin/wsdd", line 905, in __init__
    super().__init__(mch.listen_address, RequestHandlerClass)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/bin/wsdd", line 911, in server_bind
    super().server_bind()
  File "/usr/lib/python3.9/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by christgau** [comment]
> File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
>     self.socket.bind(self.server_address)
> OSError: [Errno 98] Address already in use

Could you please check if wsdd isn't running already? The socket wsdd binds to is already in use. So either wsdd has been started (e.g. by systemd) or another process occupies that port. You can issue `ss -tlnp | fgrep 5359`, e.g. to look at the ports...

**Comment by Spectroxx** [comment]
My bad, that was the issue. Thank you, I completely overlooked that.

**Comment by Spectroxx** [comment]
Does wsdd support hirsute? I got it running on popOS and samba is configured properly, it's just my linux machine isn't displaying on windows? My windows machine has SMB enabled, I'm not sure what's wrong.

**Comment by christgau** [comment]
Could you please open a new issue for that since the original one was resolved?
