### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by nelem** [christgau/wsdd#140]
Probably a noob error but I get an exception with whatever invocation parameters

wsdd - Web Service Discovery Daemon, v0.7.0 on FreeNAS 11.1-STABLE FreeBSD 11.1-STABLE

```
Traceback (most recent call last):
  File "./wsdd", line 1948, in <module>
    sys.exit(main())
  File "./wsdd", line 1905, in main
    nm = create_address_monitor(platform.system(), aio_loop)
  File "./wsdd", line 1890, in create_address_monitor
    return RouteSocketAddressMonitor(aio_loop)
  File "./wsdd", line 1201, in __call__
    obj.enumerate()
  File "./wsdd", line 1247, in enumerate
    self.do_enumerate()
  File "./wsdd", line 1614, in do_enumerate
    self.parse_route_socket_response(rt_buf.raw, True)
  File "./wsdd", line 1648, in parse_route_socket_response
    new_intf = self.parse_addrs(buf, sa_offset, offset + rtm_len, intf, addr_mask, rtm_type, intf_flags)
  File "./wsdd", line 1682, in parse_addrs
    elif intf in self.intf_blacklist:
  File "./wsdd", line 84, in __eq__
    return self._name == other.name
AttributeError: 'str' object has no attribute 'name'
```
Any help appreciated.

**Comment by christgau** [comment]
Maybe unrelated but could please check the Python version in use? FreeNAS/BSD 11.1 appears to be a little dated. You need at least Python 3.7 and maybe the routing socket stuff does not work on that FreeBSD version as well.

**Comment by nelem** [comment]
It's Python 3.6.3.

**Comment by christgau** [comment]
> It's Python 3.6.3.

That's too old. If the problem occurs with a more recent version (at least 3.7, as said) you may open the issue again.
