### ISSUE TITLE
ValueError on UUID parsing

### ISSUE THREAD

**Issue by grawity** [christgau/wsdd#226]
My system is running wsdd 0.8 as part of gvfs-wsdd. I have an _old_ IP camera (a PLANET ICA-HM101 from around ~2013) connected to the LAN, which sends out WSD advertisements as part of its ONVIF support. Every time wsdd receives one, it logs:

```
Jan 01 01:38:21 midnight gvfsd[4776]: 2025-01-01 01:38:21,817:wsdd WARNING(pid 4776): could not fetch metadata from: http://10.147.2.129/onvif/device_service HTTP Error 400: Bad Request
```

I suppose that's a camera issue. But when I went to _disable_ ONVIF support in the camera, it sent a `Bye` advertisement which caused an error in wsdd itself:

```
Jan 01 01:38:27 midnight gvfsd[4776]: 2025-01-01 01:38:27,632:asyncio ERROR(pid 4776): Exception in callback MulticastHandler.read_socket(<socket.socke...5.250', 3702)>)
Jan 01 01:38:27 midnight gvfsd[4776]: handle: <Handle MulticastHandler.read_socket(<socket.socke...5.250', 3702)>)>
Jan 01 01:38:27 midnight gvfsd[4776]: Traceback (most recent call last):
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/bin/wsdd", line 330, in read_socket
Jan 01 01:38:27 midnight gvfsd[4776]:     handler.handle_packet(msg.decode('utf-8'), address)
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/bin/wsdd", line 742, in handle_packet
Jan 01 01:38:27 midnight gvfsd[4776]:     self.handle_message(msg, src)
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/bin/wsdd", line 534, in handle_message
Jan 01 01:38:27 midnight gvfsd[4776]:     retval = handler(header, body)
Jan 01 01:38:27 midnight gvfsd[4776]:              ^^^^^^^^^^^^^^^^^^^^^
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/bin/wsdd", line 775, in handle_bye
Jan 01 01:38:27 midnight gvfsd[4776]:     device_uuid = str(uuid.UUID(endpoint))
Jan 01 01:38:27 midnight gvfsd[4776]:                       ^^^^^^^^^^^^^^^^^^^
Jan 01 01:38:27 midnight gvfsd[4776]:   File "/usr/lib/python3.12/uuid.py", line 178, in __init__
Jan 01 01:38:27 midnight gvfsd[4776]: ValueError: badly formed hexadecimal UUID string
```

This is the advertisement on port 3702 that seems to trigger the backtrace:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"
            xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery"
            xmlns:dn="http://www.onvif.org/ver10/network/wsdl"
            xmlns:s="http://www.w3.org/2003/05/soap-envelope">
  <s:Header>
    <a:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Bye</a:Action>
    <a:MessageID>uuid:bed53c19-f859-351f-e8ce-44cdbe1ef15b</a:MessageID>
    <a:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To>
    <d:AppSequence InstanceId="1077004800" MessageNumber="1"/>
  </s:Header>
  <s:Body>
    <d:Bye>
      <a:EndpointReference>
        <a:Address>uuid:wsdiscovery_NetworkCamera-00304FA1545F</a:Address>
      </a:EndpointReference>
    </d:Bye>
  </s:Body>
</s:Envelope>
```

If relevant, the regular `Hello` advertisements look like this, and they don't trigger any parse errors:

```xml
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing"
            xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery"
            xmlns:dn="http://www.onvif.org/ver10/network/wsdl"
            xmlns:s="http://www.w3.org/2003/05/soap-envelope">
  <s:Header>
    <a:Action>http://schemas.xmlsoap.org/ws/2005/04/discovery/Hello</a:Action>
    <a:MessageID>uuid:0edc26cf-edc0-1a90-dcc3-fcec5db1db79</a:MessageID>
    <a:To>urn:schemas-xmlsoap-org:ws:2005:04:discovery</a:To>
    <d:AppSequence InstanceId="1077004800" MessageNumber="23"/>
  </s:Header>
  <s:Body>
    <d:Hello>
      <a:EndpointReference>
        <a:Address>uuid:wsdiscovery_NetworkCamera-00304FA1545F</a:Address>
      </a:EndpointReference>
      <d:Types>dn:NetworkVideoTransmitter</d:Types>
      <d:Scopes> onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/type/audio_encoder onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/hardware/ICA-HM101 onvif://www.onvif.org/name/PLANETICA-HM101 onvif://www.onvif.org/location/ </d:Scopes>
      <d:XAddrs>http://10.147.2.129/onvif/device_service</d:XAddrs>
      <d:MetadataVersion>1</d:MetadataVersion>
    </d:Hello>
  </s:Body>
</s:Envelope>
```

**Comment by christgau** [comment]
Well, apparently, this

> ```
>     <d:Bye>
>       <a:EndpointReference>
>         <a:Address>uuid:wsdiscovery_NetworkCamera-00304FA1545F</a:Address>
>       </a:EndpointReference>
>     </d:Bye>
> ```

does not contain a valid UUID. However, [WSA addressing](https://www.w3.org/submissions/ws-addressing/#_Toc77464318) does not require it to be an UUID and the implementation of wsdd might be to restrictive in terms of the standard (or sloppy in the was it was done). I'll take a look...
