### ISSUE TITLE
Error start service with using libseccomp v2.5.1

### ISSUE THREAD

**Issue by Izorkin** [christgau/wsdd#75]
After updating libseccomp library from version 2.5.0 to 2.5.1, error starting wsdd service:
```
wsdd[758]: Traceback (most recent call last):
wsdd[758]:   File "/nix/store/qjz0v56g21h9skg678rsdc5wxz31dci2-wsdd-0.6.2/bin/.wsdd-wrapped", line 1684, in <module>
wsdd[758]:     sys.exit(main())
wsdd[758]:   File "/nix/store/qjz0v56g21h9skg678rsdc5wxz31dci2-wsdd-0.6.2/bin/.wsdd-wrapped", line 1629, in main
wsdd[758]:     nm = NetlinkAddressMonitor(s)
wsdd[758]:   File "/nix/store/qjz0v56g21h9skg678rsdc5wxz31dci2-wsdd-0.6.2/bin/.wsdd-wrapped", line 957, in __call__
wsdd[758]:     obj = super().__call__(*args, **kwargs)
wsdd[758]:   File "/nix/store/qjz0v56g21h9skg678rsdc5wxz31dci2-wsdd-0.6.2/bin/.wsdd-wrapped", line 1162, in __init__
wsdd[758]:     self.socket = socket.socket(socket.AF_NETLINK, socket.SOCK_RAW,
wsdd[758]:   File "/nix/store/jdp800qwb3v330ggl6iq722ww96q2444-python3-3.8.6/lib/python3.8/socket.py", line 231, in __init__
wsdd[758]:     _socket.socket.__init__(self, family, type, proto, fileno)
wsdd[758]: OSError: [Errno 97] Address family not supported by protocol
systemd[1]: samba-wsdd.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by christgau** [comment]
wsdd does not interact with libseccomp on its own, so any update on the library should not have an impact on wsdd - at least from its side. 

From the log it appears that wsdd is running "wrapped". Is it possible that it runs inside a container or any other restricted environment where some system calls are blocked via libseccomp? For example, the `socket`call with netlink family, which is apparently used by wsdd, might be forbidden as a security measure.

**Comment by Izorkin** [comment]
I have systemd used to run wsdd. Service configuration:
```
[Unit]
After=network.target
Description=Web Services Dynamic Discovery host daemon

[Service]
Environment="LOCALE_ARCHIVE=/nix/store/k1yac6z5x9qqrrxf89xmwp38rs7snhjj-glibc-locales-2.32-10/lib/locale/locale-archive"
Environment="PATH=/nix/store/8gsdifv2q3hnq42v7ddk38nmiagmjd6c-coreutils-8.32/bin:/nix/store/khvalqldk47cx8d54gik9jrqsinzmwng-findutils-4.7.0/bin:/nix/store/134fdr0yrl4wgrrasxn9d3s8vzcm5lxq-gnugrep-3.6/bin:/nix/store/q3ppqi1npx3vnsdlk8hk9s4p3adc4ygp-gnused-4.8/bin:/nix/store/vl3mww1ns6n7pw1w03hcb2qi9563znkp-systemd-247/bin:/nix/store/8gsdifv2q3hnq42v7ddk38nmiagmjd6c-coreutils-8.32/sbin:/nix/store/khvalqldk47cx8d54gik9jrqsinzmwng-findutils-4.7.0/sbin:/nix/store/134fdr0yrl4wgrrasxn9d3s8vzcm5lxq-gnugrep-3.6/sbin:/nix/store/q3ppqi1npx3vnsdlk8hk9s4p3adc4ygp-gnused-4.8/sbin:/nix/store/vl3mww1ns6n7pw1w03hcb2qi9563znkp-systemd-247/sbin"
Environment="TZDIR=/nix/store/xylnr0mwfqkzs2pzv2ig6hb6kawi1ypq-tzdata-2020c/share/zoneinfo"

CapabilityBoundingSet=
DynamicUser=true
ExecStart=/nix/store/qjz0v56g21h9skg678rsdc5wxz31dci2-wsdd-0.6.2/bin/wsdd --interface 'eno1' \
                      --hoplimit '2' \
                      --workgroup 'WORKGROUP' \
                      --hostname 'EXAMPLE' \
                      '--ipv4only'

LockPersonality=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
PrivateDevices=true
PrivateMounts=true
PrivateTmp=true
PrivateUsers=false
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectSystem=strict
RestrictAddressFamilies=AF_UNIX
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=AF_INET6
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
RuntimeDirectory=wsdd
RuntimeDirectoryMode=0750
SystemCallArchitectures=native
SystemCallFilter=~@clock @cpu-emulation @debug @module @mount @obsolete @privileged @raw-io @reboot @resources @swap
Type=simple
UMask=0027
```

Socket calls allowed - `RestrictAddressFamilies=AF_UNIX`

After deleting these lines:
```
RestrictAddressFamilies=AF_UNIX
RestrictAddressFamilies=AF_INET
RestrictAddressFamilies=AF_INET6
```
wsdd service starts normally.
This is a bug in libseccomp library?

**Comment by christgau** [comment]
No, IMO there is no bug in libseccomp related to this issue. The unit is missing one address family, the three you listed are not sufficient. From the error log you see

> `wsdd[758]:     self.socket = socket.socket(socket.AF_NETLINK, socket.SOCK_RAW,`

Try adding a `RestrictAddressFamilies=AF_NETLINK` (my guess) to the unit file and let's see if it works.

Additionally, IIRC UNIX sockets are actively only used in case one starts wsdd in the discovery mode which you don't do. If Python or any loaded library does not do something different under the hood I would assume you can delete the line with AF_UNIX.

**Comment by Izorkin** [comment]
Thanks for help. With `AF_NETLINK` worked. Need add `SOCK_RAW` and `NETLINK_ROUTE` ?

**Comment by christgau** [comment]
> With `AF_NETLINK` worked. 

Great.

> Need add `SOCK_RAW` and `NETLINK_ROUTE` ?

No. These aren't address families.

**Comment by Izorkin** [comment]
Created a PR to fix the WSDD service in NixOS - https://github.com/NixOS/nixpkgs/pull/107112
